name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    environment:
      name: pypi.org
      url: https://pypi.org/project/dxh-py/

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build tools
      run: python -m pip install --upgrade pip build

    - name: Build distributions
      run: python -m build --sdist --wheel --outdir dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}